spring:
  application:
    name: lx-sale-server
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分
  datasource:
    url: jdbc:mysql://82.156.51.218:3306/db_fl_trading?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: lxA_Pu%oS8Pl
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.81.1:8848
    sentinel:
      transport:
        port: 9900
        dashboard: localhost:7777
  redis:
    host: 192.168.159.128
    port: 6379
    password:
server:
  port: 9103
  tomcat:
    max-threads: 10
feign:
  sentinel:
    enabled: true
rocketmq:
  name-server: 127.0.0.1:9876 #rocketMQ服务的地址
  producer:
    group: sale-order # 生产者组
# Seata 配置项，对应 SeataProperties 类
seata:
  application-id: ${spring.application.name} # Seata 应用编号，默认为 ${spring.application.name}
  tx-service-group: my_test_tx_group # Seata 事务组编号，用于 TC 集群名
  # 服务配置项，对应 ServiceProperties 类
  service:
    # 虚拟组和分组的映射  my_test_tx_group
    vgroup-mapping:
      my_test_tx_group: default
    # 分组和 Seata 服务的映射
    grouplist:
      default: 127.0.0.1:8091
    # Seata 注册中心配置项，对应 RegistryProperties 类
    registry:
      type: nacos # 注册中心类型，默认为 file
      nacos:
        cluster: default # 使用的 Seata 分组
        serverAddr: 82.156.71.248 # Nacos 服务地址
